// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN6bM_eIiMP0E-RAnmoDDLD0eO6iDH-5s',
    appId: '1:438346985754:web:bd7940010035b6c5747ca3',
    messagingSenderId: '438346985754',
    projectId: 'mentalsustainability-974e3',
    authDomain: 'mentalsustainability-974e3.firebaseapp.com',
    storageBucket: 'mentalsustainability-974e3.firebasestorage.app',
    measurementId: 'G-GYF51HSSKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALlBZ_6ZbxtpTEjawrm-D1skdMU01ruik',
    appId: '1:438346985754:android:17b242f7b9f67d38747ca3',
    messagingSenderId: '438346985754',
    projectId: 'mentalsustainability-974e3',
    storageBucket: 'mentalsustainability-974e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0gp6jozQJ6jqMiJmW4XWjJziUFpcCbmA',
    appId: '1:438346985754:ios:ae0ab67f896831b4747ca3',
    messagingSenderId: '438346985754',
    projectId: 'mentalsustainability-974e3',
    storageBucket: 'mentalsustainability-974e3.firebasestorage.app',
    iosBundleId: 'com.example.mentalsustainability',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0gp6jozQJ6jqMiJmW4XWjJziUFpcCbmA',
    appId: '1:438346985754:ios:ae0ab67f896831b4747ca3',
    messagingSenderId: '438346985754',
    projectId: 'mentalsustainability-974e3',
    storageBucket: 'mentalsustainability-974e3.firebasestorage.app',
    iosBundleId: 'com.example.mentalsustainability',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN6bM_eIiMP0E-RAnmoDDLD0eO6iDH-5s',
    appId: '1:438346985754:web:26ade2dc2ea21880747ca3',
    messagingSenderId: '438346985754',
    projectId: 'mentalsustainability-974e3',
    authDomain: 'mentalsustainability-974e3.firebaseapp.com',
    storageBucket: 'mentalsustainability-974e3.firebasestorage.app',
    measurementId: 'G-5HFP8QVP0P',
  );
}
